#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true
# Rodar o phpstan
for FILE in $STAGED_FILES
do
    ./vendor/bin/phpstan analyse "${FILE}" > /dev/null >&1;
    if [ $? -ne 0 ]; then
        echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
        exit 1;
    fi;
done;

# rodar os testes
for FILE in $STAGED_FILES
 do
     php artisan test "${FILE}"
     if [ $? -ne 0 ]; then
         echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
         exit 1;
     fi;
done;

# Formatar cada arquivo alterado usando o Laravel Pint
for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;
